pipeline {
    agent any

    stages {
        stage('Compile') {
            steps {
                dir('armstrong-number-c') {
                    sh 'make'
                } 
            }
        }
        stage('cppcheck') {
            steps {
                dir('armstrong-number-c') {
                    sh 'make cppcheck-xml'
                }
            }
        }
    }

    post {
        always {
            //publishCppcheck ignoreBlankFiles: true, pattern: 'armstrong-number-c/reports/cppcheck/report.xml'
              recordIssues enabledForFailure: true, tool: cppCheck(pattern: 'armstrong-number-c/reports/cppcheck/*.xml')
        }
        success {
            archiveArtifacts artifacts: 'armstrong-number-c/is_armstrong_number', followSymlinks: false
        }
    }
}
